### ISSUE TITLE
Issues installing slycot via pip

### ISSUE THREAD

**Issue by PSchneider96** [python-control/Slycot#155] opened 2021-05-17 06:27 UTC
Hello,

Currently trying to install slycot with "pip install slycot"

While running "pip install slycot", I get the following output:

```
================================================================================
_C:\Windows\system32>pip install slycot
Collecting slycot
  Using cached slycot-0.4.0.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in c:\users\psc\appdata\local\programs\python\python39\lib\site-packages (from slycot) (1.20.3)
Building wheels for collected packages: slycot
  Building wheel for slycot (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\psc\appdata\local\programs\python\python39\python.exe' 'c:\users\psc\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\psc\AppData\Local\Temp\tmp_pm1h_ju'
       cwd: C:\Users\psc\AppData\Local\Temp\pip-install-g41g7ty1\slycot_37cc017271c84d17ac02eef4e57cb82e
  Complete output (56 lines):
  Not searching for unused variables given on the command line.
  -- The C compiler identification is unknown
  CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
    The CMAKE_C_COMPILER:

      cl

    is not a full path and was not found in the PATH.

    To use the NMake generator with Visual C++, cmake must be run from a shell
    that can use the compiler cl from the command line.  This environment is
    unable to invoke the cl compiler.  To fix this problem, run cmake from the
    Visual Studio Command Prompt (vcvarsall.bat).

    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/psc/AppData/Local/Temp/pip-install-g41g7ty1/slycot_37cc017271c84d17ac02eef4e57cb82e/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/psc/AppData/Local/Temp/pip-install-g41g7ty1/slycot_37cc017271c84d17ac02eef4e57cb82e/_cmake_test_compile/build/CMakeFiles/CMakeError.log".
  FC ('-DCMAKE_Fortran_COMPILER=', 'c:/users/psc/appdata/local/programs/python/python39/Library/bin/flang.exe')
  F2PY ('-DF2PY_EXECUTABLE=', 'c:/users/psc/appdata/local/programs/python/python39/Scripts/f2py.exe')
  NUMPY_INCLUDE ('-DNumPy_INCLUDE_DIR=', 'c:/users/psc/appdata/local/programs/python/python39/Include')
  ['-DSLYCOT_VERSION:STRING=0.4.0', '-DGIT_REVISION:STRING=ac0944b363a6cfcc0c3d5128cdd484d74173aa3b', '-DISRELEASE:STRING=True', '-DFULL_VERSION=0.4.0.gitac0944b', '-GNMake Makefiles', '-DCMAKE_Fortran_COMPILER=c:/users/psc/appdata/local/programs/python/python39/Library/bin/flang.exe', '-DF2PY_EXECUTABLE=c:/users/psc/appdata/local/programs/python/python39/Scripts/f2py.exe', '-DNumPy_INCLUDE_DIR=c:/users/psc/appdata/local/programs/python/python39/Include', '-DCMAKE_Fortran_SIMULATE_VERSION=5.0.0', '-DCMAKE_Fortran_COMPILER_ID=Flang', '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON']


  --------------------------------------------------------------------------------
  -- Trying "NMake Makefiles (Visual Studio 15 2017 Win64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "NMake Makefiles (Visual Studio 15 2017 Win64 v141)" generator - failure
  --------------------------------------------------------------------------------

  ********************************************************************************
  scikit-build could not get a working generator for your system. Aborting build.

  Building windows wheels for Python 3.9 requires Microsoft Visual Studio 2017.
  Get it with "Visual Studio 2017":

    https://visualstudio.microsoft.com/vs/

  ********************************************************************************
  ----------------------------------------
  ERROR: Failed building wheel for slycot
Failed to build slycot
ERROR: Could not build wheels for slycot which use PEP 517 and cannot be installed directly_
================================================================================
```

However, I cannot make sense of the output. I installed VS 2017 with the correct version v141.
(I run this code in cmd, VS, ... same issue)

Is there something else to do? Set path for VS or CMake,...?

Thanks!

**Comment by bnavigator** [comment] 2021-05-17 09:22
Hi,

Because we do not provide Slycot wheels on PyPI, `pip install slycot` tries to compile the source distribution.

As the README says, compiling from source on Windows is tricky.

https://github.com/python-control/Slycot/blob/master/README.rst#with-setuptools-in-a-conda-environment-windows

If you choose to not use conda as your environment, it is even trickier to get all the build requirements: BLAS/LAPACK headers, Numpy and Python headers, and most importantly a working build toolchain where NMake can find the VS C compiler.

The error message should give you a pointer into the right direction:

> ```
>    The CMAKE_C_COMPILER:
>
>      cl
>
>    is not a full path and was not found in the PATH.
>
>    To use the NMake generator with Visual C++, cmake must be run from a shell
>    that can use the compiler cl from the command line.  This environment is
>    unable to invoke the cl compiler.  To fix this problem, run cmake from the
>    Visual Studio Command Prompt (vcvarsall.bat).
>
>    Tell CMake where to find the compiler by setting either the environment
>    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
>    the compiler, or to the compiler name if it is in the PATH.
> ```


This is what the README is referring to by 

> On Windows, you need to install [Microsoft Visual C++ 14.x](https://wiki.python.org/moin/WindowsCompilers)  provided e.g.
  by [Microsoft Visual Studio](https://visualstudio.microsoft.com/de/vs/).  To build, you'll need a command shell setup
  for ... the Visual Studio build tools.  See ... [Microsoft Visual Studio setup](https://docs.microsoft.com/en-us/cpp/build/setting-the-path-and-environment-variables-for-command-line-builds) for information on this.

Windows users are encouraged to make use of the pre-built packages on conda-forge.

**Comment by bnavigator** [comment] 2021-05-29 09:02
Closing, because this is not really a bug in Slycot.

**Closed by bnavigator** 2021-05-29 09:02 UTC
Labels: build system

**Comment by OrangeDog** [comment] 2021-12-17 13:36
> we do not provide Slycot wheels on PyPI

Could you? It would be very helpful and save a huge amount of effort of everyone trying to build it themselves.

**Comment by roryyorke** [comment] 2021-12-18 13:11
We don't publish wheels because we don't know how to build them.

I've tried and failed to build wheels for Windows before; if I recall correctly one basically has to bundle a BLAS&LAPACK library in the wheel, and I couldn't figure out how to do it.

**Comment by bnavigator** [comment] 2021-12-18 13:33
The wheels linked above also depend on a consistent environment with all those packages.

The situation might have changed for the better since the last time it was attempted to also build wheels for Slycot. [NumPy publishes wheels on PyPI too](https://numpy.org/doc/stable/dev/releasing.html#supported-platforms-and-versions). If someone can come up with a reliable method to publish wheels compatible with those, feel free to contribute.

I am not a big fan of Anaconda, but for Windows, it is the best thing you can get. It solves all the problems of getting a compiled Slycot working with a  BLAS/LAPACK which is also compatible with the used NumPy.

**Comment by RGD2** [comment] 2025-09-03 23:25
> We don't publish wheels because we don't know how to build them.
> 
> I've tried and failed to build wheels for Windows before; if I recall correctly one basically has to bundle a BLAS&LAPACK library in the wheel, and I couldn't figure out how to do it.

You may want to consider switching to using the BLAS compatibility layer of BLIS - which is written in pure C99 with no dependancies.

This also removes needing a fortran compiler.

**Comment by RGD2** [comment] 2025-09-04 01:46
> I am not a big fan of Anaconda, but for Windows, it is the best thing you can get. It solves all the problems of getting a compiled Slycot working with a BLAS/LAPACK which is also compatible with the used NumPy.

I'm definitely an anti-fan of Anaconda, having been bitten by it before (wanton breakage of updates, mostly so they can generate support work for themselves).

Also, it's not the best thing for Windows: WSL is, since it means you only need to support staid Debian stable. Support which is just knowing what one-liner of apt-get packages is needed to have all the build-depends.

So for Windows users - install Debian Stable either from the Microsoft Store app or using winget. Run it, give yourself a username and password, then the rest can just be to paste in and run a few instructions.

Simple stuff like maybe add contrib, update it with apt update; apt upgrade, then do the apt install <....> line. (i also recommend getting python itself using pyenv, which also works extremely well there: use of tools like this, also nvm for nodejs, etc, allows fresh versions of important deps without having to run a bleeding-edge distro).

And all will henceforth be well. 

Most everyone in the data science community is using things like jupyter lab, which, being server-side, run actually demonstably far better in WSL (especially WSL 2.0) than they do natively in windows.

Of course, since the UI is a webui, the browser is the usual native one, so there's no performance compromise there either.

Maintenance is just do the `apt update; apt upgrade` occasionally, or even just only as a first step whenever problems arise. Very much unlike conda, this never breaks things. (apt full-upgrade might, but that gives you power over when that happens: never out of the blue). 

Otherwise Microsoft maintains WSL. 

This fills in Anaconda's original real niche, its raison d'etre, in a way that is more sustainable and reliable. (And which cuts out a greedy, unnecessary, problem-causing middle-man).

Maybe one day winget will become as capable as apt-get, which would also fill in that same niche*. But for the time being, supporting nearly everyone in one easily accessible common way is good.  

*Since Windows programmers think it's still standard procedure to have to manually find, download, extract and place dependancy libraries, nothing on the platform helps with this.  Even cmake does nothing to facilitate this, other than complaining that it can't find each specific thing.  (If you don't know, in the freebsd ports system, which works like pip, `make` there *does* know how to automatically find, download, extract, special-patch-for-freebsd, configure, compile and install dependancies, completely automatically. This was so impressive, the gentoo linux project copied it, for their portage system, re-implemented in Python rather than makefiles. Point being, cmake *certainly* could have been like this. Rust's `cargo` *is*, which BTW, also works under Debian stable on WSL). 

So, it might be a while before they catch up, if they ever do (because, again, WSL is a thing, so there isn't actually a need anymore).

And MacOS has fink and homebrew, which can even be used together. Between them they manage to have dependancy coverage almost as good as apt does, so MacOS doesn't need conda either.

I say Debian Stable rather than Ubuntu, because it will get much the same issues as conda: It's owning corporation has a profit motive to get paid for what end up being more often treating symptoms, rather than curing diseases. 

The conundrum is: If they cure the disease, they'll no longer have income from treating its symptoms. It doesn't matter how good intentions are to avoid this starting out, eventually the corporation will just decide to delete the 'be not evil' part of their constitution, for the totally understandable reason of profitability.

Mint is not really applicable here: It's for non-CLI desktop conversion, which is also what Ubuntu originally claimed to be its niche. On WSL, there's no real advantage over Debian itself. And even that isn't much of a difference on an actual desktop these days either: The CLI is very much a strawman.

All of which is just griping, sorry: Yet another Python library that almost solves my problem, except it's broken because pip install fails, and this can be traced to its developers getting lazy because conda exists and wastes their efforts. 

Then not even having the common curtesy to properly define the clean built environment. (Clean here means, has never run the anaconda official install 'script' binary).

Pro tip: You project will get a lot more development help the more convenient you make it to spin up a minimal and very clean environment, which is tested and confirmed to actually build the source in reliably. This is why continous integration (CI) is such a priority. Yours is broken, this is not good (but at least you have one).

PS: You want to avoid specifiying either `ubuntu-latest` or `debian-stable` directly in scripts, because they are moving targets and will eventually break your work (this might be why your CI is broken): Use specific named versions, preferably choosing the codename of the current LTS releases:  These would be `debian-trixie` and `ubuntu-24.04.3`. but you might find easier success with older stable versions such as `debian-bullseye` or `ubuntu-20.04`
