### ISSUE TITLE
DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by abhilashknair** [python-control/Slycot#46] opened 2019-01-28 12:06 UTC
Hi,
I have successfully installed the slycot package using a wheel file. I am try to import slycot in Python. I get the following error log. Could someone please help me understand the issue here? Thanks! :)
>>> import slycot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\slycot\__init__.py", line 18, in <module>
    from .analysis import ab01nd,ab05md,ab05nd,ab07nd,ab08nd, \
  File "C:\Python27\lib\site-packages\slycot\analysis.py", line 21, in <module>
    from . import _wrapper
ImportError: DLL load failed: The specified module could not be found.

**Comment by repagh** [comment] 2019-02-01 11:03
Did you create this wheel file or get it from somewhere?
What version of slycot?
Note that slycot for windows is pretty difficult to compile, you might want to use the anaconda version, and pull a compiled package from my conda channel (repa). 

p.s. why are you still using Python 2.7?

**Comment by T-BA** [comment] 2019-04-01 10:02
Hi, I also have an issue with the DLL, on windows 10, tried with both python 3.5.6 and 3.6.3 (our default version).

My steps with a clean conda environment:
```
conda create -n py35 python=3.5 numpy
conda config --append channels conda-forge
conda install -c repa slycot
conda install control
```

When I attempt to run the following minimal example:
```
from control import *
num = [[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]]
den = [[[9., 8., 7.], [6., 5., 4.]], [[3., 2., 1.], [-1., -2., -3.]]]
sys1 = tf(num, den)
tf2ss(sys1)
```
I get the error:
Traceback (most recent call last):
  File "<tmp 1>", line 9, in <module>
    tf2ss(sys1)
  File "C:\Python\Conda\envs\py35\lib\site-packages\control\statesp.py", line 1245, in tf2ss
    return _convertToStateSpace(sys)
  File "C:\Python\Conda\envs\py35\lib\site-packages\control\statesp.py", line 830, in _convertToStateSpace
    raise TypeError("No support for MIMO without slycot")
TypeError: No support for MIMO without slycot

When I attempt to import slycot, I get:
>>> import slycot
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Python\Conda\envs\py35\lib\site-packages\slycot\__init__.py", line 16, in <module>
    from .analysis import ab01nd,ab05md,ab05nd,ab07nd,ab08nd, \
  File "C:\Python\Conda\envs\py35\lib\site-packages\slycot\analysis.py", line 21, in <module>
    from . import _wrapper
ImportError: DLL load failed: The specified module could not be found.


Do you have any sugestions? If you need any additional info please let me know.

**Comment by WRadigan** [comment] 2019-04-16 21:59
Similar issue here.  I tried installing the Python 3.5 / Win64 Wheel from the link below into my Enthought Canopy environment (Canopy v2.1.9).  Pip ran without error, but import failed afterwards.  

Also, what's the difference between Enthought Canopy and the Anaconda Python Distribution?  I'm a mid-level user (at best) and I'm happy to try something new if my toolset is just a bit old.

https://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by bnavigator** [comment] 2019-06-21 21:39
I looked into the wheel packages from that last link. I am not sure, but it seems that the compiled library wrapper in there has the wrong name. Go to your site-packages\slycot directory and copy the file named _wrapper.cp36-win-amd64.pyd to _wrapper.pyd

Or switch to Anaconda.

**Comment by tstorek** [comment] 2019-08-08 11:42
Hi,
i have the same issue. I use anaconda3. I already tried to set up a fresh environment with python3.7 . 
I copied the _wrapper.cp37-win-amd64.pyd to _wrapper.pyd. But same result. 
Before that I tried to use the conda package from conda-forge.

But still, slycot cannot find that stupid DLL. 

I am a bit frustrated already. Since I am realy interested in the MIMO stuff I would like to test it.

Thanks for any help.

**Comment by bnavigator** [comment] 2019-08-08 12:50
What's the version of your slycot package from conda-forge?

The most recent file for win64 slycot-0.3.5.0 for py37 does not have a `_wrapper.cp37-win-amd64.pyd` but a correctly named `_wrapper.pyd` and `_wrapper.lib` file in `site-packages/slycot`
https://anaconda.org/conda-forge/slycot/files

**Comment by tstorek** [comment] 2019-08-08 13:09
Hi,
it worked now. But seriously don't have the slightest clue why :D  
What I did: 
- Setting up fresh environment
- installing numpy and all other packages from conda
- Then installed slycot again with conda (latest)(slycot-0.3.5.0-py3.7-win-amd64)

And surprisingly it works now. But I as I said, no idea why. Maybe it is the order in that I installed the packages, but I thought that conda would check that for me.

**Comment by bnavigator** [comment] 2019-08-08 13:15
Order is not important, conda should check all the necessary dependencies. Just install slycot and control in a fresh environment and numpy etc gets pulled in automatically.

Just don't mix different conda channels and manually downloaded wheels if you don't know exactly what you are doing.

**Comment by tstorek** [comment] 2019-08-08 13:20
Okay, thanks for the info. Maybe in this case it was a lucky punch for me:) In future I will try the put the exact channel. However, when I did before it did not work so. I am happy now anyway.

**Comment by bnavigator** [comment] 2020-05-30 22:45
Closing with version 0.4.0 having been released. Feel free to re-open, if you believe the issue is not resolved.

**Closed by bnavigator** 2020-05-30 22:45 UTC

**Comment by paolodemo** [comment] 2022-03-18 12:59
I'm having this issue with Anaconda3-2021.11-Windows-x86_64.
I installed manually slycot downloading from: [https://anaconda.org/conda-forge/slycot/0.4.0.0/download/win-64/slycot-0.4.0.0-py39h6635163_8.tar.bz2](https://anaconda.org/conda-forge/slycot/0.4.0.0/download/win-64/slycot-0.4.0.0-py39h6635163_8.tar.bz2)
and installing with:
`conda install slycot-0.4.0.0-py39h6635163_8.tar.bz2`

I obtain the following error
```
(base) C:\Users\paolo cacciagrano\Downloads>python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import slycot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\paolo cacciagrano\Anaconda3\lib\site-packages\slycot\__init__.py", line 16, in <module>
    from .analysis import ab01nd, ab05md, ab05nd, ab07nd, ab08nd, ab08nz
  File "C:\Users\paolo cacciagrano\Anaconda3\lib\site-packages\slycot\analysis.py", line 20, in <module>
    from . import _wrapper
ImportError: DLL load failed while importing _wrapper: The specified module could not be found.
```
How can I work around ?
